// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM5OcYNEzpGVn3FFElKKR41u_eK-SLZXE',
    appId: '1:381257159038:web:ed6d3c34741a8e7d29e32f',
    messagingSenderId: '381257159038',
    projectId: 'medifinder-bfc75',
    authDomain: 'medifinder-bfc75.firebaseapp.com',
    storageBucket: 'medifinder-bfc75.firebasestorage.app',
    measurementId: 'G-W53NXZCLLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTQSb1SED4P6xiTVEs5TjyPqsnaL3Rxs8',
    appId: '1:381257159038:android:b4e15b34eafd0d7c29e32f',
    messagingSenderId: '381257159038',
    projectId: 'medifinder-bfc75',
    storageBucket: 'medifinder-bfc75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8kIJsSptjg1zjFDDi40oRYeGPpOLxK2k',
    appId: '1:381257159038:ios:5476203be22a551c29e32f',
    messagingSenderId: '381257159038',
    projectId: 'medifinder-bfc75',
    storageBucket: 'medifinder-bfc75.firebasestorage.app',
    iosBundleId: 'com.example.mediFinderUserHomePage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8kIJsSptjg1zjFDDi40oRYeGPpOLxK2k',
    appId: '1:381257159038:ios:5476203be22a551c29e32f',
    messagingSenderId: '381257159038',
    projectId: 'medifinder-bfc75',
    storageBucket: 'medifinder-bfc75.firebasestorage.app',
    iosBundleId: 'com.example.mediFinderUserHomePage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM5OcYNEzpGVn3FFElKKR41u_eK-SLZXE',
    appId: '1:381257159038:web:cd1f605f08fef2a829e32f',
    messagingSenderId: '381257159038',
    projectId: 'medifinder-bfc75',
    authDomain: 'medifinder-bfc75.firebaseapp.com',
    storageBucket: 'medifinder-bfc75.firebasestorage.app',
    measurementId: 'G-NEX9ZLK9FM',
  );
}
